services:
  pg:
    image: postgres:16.1
    container_name: pg-parser
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      TZ: Europe/Moscow
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - parser-net

  parser:
    image: parser
    build: .
    tty: true
    stdin_open: true
    container_name: parser
    env_file: ./.env
    depends_on:
      - pg
      - redis
    environment:
      - HISTFILE=/var/log/.ash_history
    volumes:
      - gems:/usr/local/bundle
      - .:/app
      - ./log/terminal_logs:/var/log/.ash_history
    networks:
      parser-net:
    restart: unless-stopped

  good_job:
    image: good_job
    build: .
    env_file: ./.env
    container_name: good_job-parser
    entrypoint: []
    command: bundle exec good_job start
    volumes:
      - .:/app
    depends_on:
      - pg
    networks:
      - parser-net
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis-parser
    command: redis-server
    restart: unless-stopped
    networks:
      - parser-net
    volumes:
      - redis:/data

  nginx:
    image: nginx:latest
    container_name: nginx-parser
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/app
    depends_on:
      - parser
    networks:
      parser-net:
      proxy-net:
        ipv4_address: 172.29.0.4
    restart: always

volumes:
  gems:
  db_data:
  redis:

networks:
  parser-net:
  proxy-net:
    external: true
