default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  database: rails_parser_development
  username: <%= ENV.fetch("DB_USER") { 'admin' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'admin' } %>

test:
  <<: *default
  database: rails_parser_test

production:
  <<: *default
  database: rails_parser_production
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
